/* ESP32-C3 memory layout */
MEMORY
{
  /* SRAM */
  RAM : ORIGIN = 0x3FC80000, LENGTH = 400K

  /* External flash */
  ROM : ORIGIN = 0x42000000, LENGTH = 4M
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
