/* ESP32-S3 memory layout */
MEMORY
{
  /* Internal SRAM - ESP32-S3 has 512KB */
  RAM : ORIGIN = 0x3FC88000, LENGTH = 320K

  /* External flash */
  ROM : ORIGIN = 0x42000000, LENGTH = 4M
}

REGION_ALIAS("REGION_TEXT", ROM);
REGION_ALIAS("REGION_RODATA", ROM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);
